name: Node CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  ci:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Installing depedencies
        run: npm install
      - name: Linting
        run: npm run lint
      - name: Run unit tests
        run: npm test
      - name: Build the app
        run: npm run build
